channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.13.2
  - joblib==1.4.2
  - pandas==2.2.2
  - psutil==5.9.0
  - scikit-learn==1.5.0
  - threadpoolctl==3.5.0
  - xgboost==2.0.3
name: mlflow-env
